source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'
gem 'pg'
gem 'silent-postgres'
gem 'unicorn'

# Assets
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'
gem 'jquery-rails'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :development, :test do
  gem 'guard'
  gem 'rb-fsevent'
  gem 'activerecord-nulldb-adapter', :git => 'git://github.com/joakimk/nulldb.git'
  gem 'rspec-rails'
  gem 'spork', '~> 0.9.0.rc'
  gem 'guard-spork'
  gem 'guard-rspec'
  gem 'engineyard'
  gem 'fabrication'
  gem 'capybara'
  gem 'akephalos', :git => 'https://github.com/Nerian/akephalos.git', :ref => "2a7deddf79fe1d6055ba"
end

